### ISSUE TITLE
Project does not build on clang version 6.0.0-1ubuntu2

### ISSUE THREAD

**Issue by xthexder** [microsoft/Azure-Kinect-Sensor-SDK#275]
This project does not built on the linux subsystem for windows running `Ubuntu 18.04.1 LTS`
The latest version of clang available (6.0.0-1ubuntu2) outputs the following errors:

```
../src/transformation/rgbz.c:107:29: error: implicit conversion increases floating-point precision: 'float' to 'long double' [-Werror,-Wdouble-promotion]
    if (depth == 0 || isnan(context->xy_tables->x_table[depth_index]))
                      ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/math.h:644:46: note: expanded from macro 'isnan'
#  define isnan(x) __MATH_TG ((x), __isnan, (x))
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/usr/include/math.h:562:16: note: expanded from macro '__MATH_TG'
   : FUNC ## l ARGS)
     ~~~~~~~~~ ^~~~
../src/transformation/rgbz.c:809:20: error: implicit conversion increases floating-point precision: 'float' to 'long double' [-Werror,-Wdouble-promotion]
        if (!isnan(x_tab))
             ~~~~~~^~~~~~
/usr/include/math.h:644:46: note: expanded from macro 'isnan'
#  define isnan(x) __MATH_TG ((x), __isnan, (x))
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/usr/include/math.h:562:16: note: expanded from macro '__MATH_TG'
   : FUNC ## l ARGS)
     ~~~~~~~~~ ^~~~
2 errors generated.
```

This looks to be a known bug in clang: https://bugzilla.redhat.com/show_bug.cgi?id=1472437
